spring:
  application:
    name: Intelli-Edu-user
  cloud:
    nacos:
      config: &nacos
        server-addr: ${NACOS_SERVER_ADDR:localhost:8848}
        namespace: ${NACOS_NAMESPACE:Intelli-Edu-backend}
        group: DEFAULT_GROUP
        username: ${NACOS_USERNAME:nacos}
        password: ${NACOS_PASSWORD:nacos}
      discovery: *nacos
  config:
    import:
      - optional:nacos:shared-redis.yaml?group=DEFAULT_GROUP&refresh=true
      - optional:nacos:shared-mybatis.yaml?group=DEFAULT_GROUP&refresh=true
      - optional:nacos:shared-postgres.yaml?group=DEFAULT_GROUP&refresh=true
      - optional:nacos:shared-jwt.yaml?group=DEFAULT_GROUP&refresh=true
      - optional:nacos:shared-log.yaml?group=DEFAULT_GROUP&refresh=true
      - optional:nacos:${spring.application.name}-${spring.profiles.active}.yaml?group=DEFAULT_GROUP&refresh=true

server:
  port: 8891
  servlet:
    context-path: /api/user
