FROM eclipse-temurin:21-jre
WORKDIR /app
COPY Intelli-Edu-Knowledge/target/Intelli-Edu-knowledge-0.0.1-SNAPSHOT.jar app.jar
EXPOSE 8895
ENTRYPOINT ["java", "-jar", "app.jar", "--spring.profiles.active=dev"]
