FROM eclipse-temurin:21-jre
WORKDIR /app
COPY Intelli-Edu-learning/target/Intelli-Edu-learning-0.0.1-SNAPSHOT.jar app.jar
EXPOSE 8896
ENTRYPOINT ["java", "-jar", "app.jar", "--spring.profiles.active=dev"]
