FROM eclipse-temurin:21-jre
WORKDIR /app
COPY Intelli-Edu-gateway/target/Intelli-Edu-gateway-0.0.1-SNAPSHOT.jar app.jar
EXPOSE 8890
ENTRYPOINT ["java", "-jar", "app.jar", "--spring.profiles.active=dev"]
